#!/usr/bin/env ruby

def process(command)
  file_contents = read_file(ARGV)

  case command
  when "-c"
    # number of bytes
    puts file_contents.bytesize
  when "-l"
    # number of lines
    puts file_contents.lines.count
  when "-w"
    # number of words
    puts file_contents.split.count
  when "-m"
    puts file_contents.size
  else
    exit
  end
end

def read_file(argv)
  filename = argv.shift
  begin
    file = File.open(filename, "r")
    file.read
  rescue Errno::ENOENT
    puts "File not found: #{filename}"
    exit
  ensure
    file&.close
  end
end

if ARGV.length == 0
  puts "Usage: ./ccwc [command] [file]"
  exit
end

if ARGV.length == 1
  file_contents = read_file(ARGV)
  puts "    #{file_contents.lines.count} #{file_contents.split.count} #{file_contents.bytesize}"
  exit
end

command = ARGV.shift
process(command)


